version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
    timezone: Turkey
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: io.github.portlek:reflection
    versions:
    - 4.0.11
    - 4.1.0
    - 4.1.1
  - dependency-name: io.github.portlek:ppom
    versions:
    - 2.3.10
    - 2.3.11
    - 2.3.4
    - 2.3.5
    - 2.3.6
    - 2.3.7
    - 2.3.8
    - 2.3.9
